// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfvRd_1Tp73IJcg-S6NJNRluhb488vhRE',
    appId: '1:991607031482:web:df3bf3a43edef57bc2e483',
    messagingSenderId: '991607031482',
    projectId: 'bobo-b1d27',
    authDomain: 'bobo-b1d27.firebaseapp.com',
    storageBucket: 'bobo-b1d27.appspot.com',
    measurementId: 'G-FBV9K15KND',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuYypaGcWe4QX9R7JihIefheLZ4zscBKk',
    appId: '1:991607031482:android:d8813f863f381c42c2e483',
    messagingSenderId: '991607031482',
    projectId: 'bobo-b1d27',
    storageBucket: 'bobo-b1d27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx6esXM1grkLLA0x6ccjWGxnuElnkSonc',
    appId: '1:991607031482:ios:4cf203dd1a53e86ac2e483',
    messagingSenderId: '991607031482',
    projectId: 'bobo-b1d27',
    storageBucket: 'bobo-b1d27.appspot.com',
    iosClientId: '991607031482-vcg99vgtuo1of90pkunql9vr1vveidiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleCaptch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx6esXM1grkLLA0x6ccjWGxnuElnkSonc',
    appId: '1:991607031482:ios:4cf203dd1a53e86ac2e483',
    messagingSenderId: '991607031482',
    projectId: 'bobo-b1d27',
    storageBucket: 'bobo-b1d27.appspot.com',
    iosClientId: '991607031482-vcg99vgtuo1of90pkunql9vr1vveidiq.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleCaptch',
  );
}
